
# .releaserc.yml
# Configuration for the python-semantic-release tool.

# Use the tag format without a "v" prefix (e.g., 1.0.0 instead of v1.0.0)
tag_format: "{version}"

# Defines the branches for which releases should be created.
branches:
  main:
    match: main

# Specifies how to bump the version based on conventional commit types.
version_toml:
  - pyproject.toml:tool.poetry.version # Assuming Poetry is used for pyproject.toml management.
                                       # Adjust if using a different build backend.
commit_parser_options:
  # Defines which commit types trigger which version bump.
  major_tags: ["BREAKING CHANGE", "breaking"]
  minor_tags: ["feat", "feature"]
  patch_tags: ["fix", "docs", "refactor", "perf", "style", "test", "build", "ci"]

# Defines the build and distribution process.
dist:
  # The command to execute to build the package artifacts.
  command: python -m build
  # The directory where the built artifacts are stored.
  path: dist/

# Defines the upload/publishing process.
upload:
  # Specifies the target repository for publishing.
  # "github" corresponds to the GitHub Releases page.
  - repository: github
  # "pypi" would be used for the Python Package Index.
  # For GitHub Packages, the repository URL is configured in pyproject.toml.